---
title: "Process Statement"
author: "Logan Jacobs"
format: html
editor: visual
---

# To reflect on my journey

My understanding of quantitative text analysis has changed drastically over the course of the semester. At the beginning, I believed that quantitative text analysis would only be working with data, and shaping data into what we needed. I didn't even think about how I was actually going to get the data, why I was doing what I was going to be doing, or how to communicate the whole procedure. I wasn't aware that there were so many steps to ensure reproducible research.

## Foundation

Over the course, I learned there was much more to quantitative text analysis, and learned how R, or any other programming language, for that matter, can be used to perform string manipulation and dataset manipulation. I learned about how reproducible research was first built up, "scaffolded", as you called it, and how it's essentially a fill-in-the-blank, allowing others to recreate the same thing and verify your results with relative ease. 

## Preparation

This is the section I originally thought was the whole of quantitative text analysis, preparation of the data. It seems odd now to say this, of course analysis is part of "quantitative text analysis", what was I thinking? Regardless, this was the step I had the most experience with. Because of my earlier background in Python, and here at Wake Forest, Java, I was very familiar with data and string manipulation in those languages. However, actually acquiring the data to do these actions on was something I never had to deal with, which might be somewhat surprising. I'm certainly glad I had the opportunity to do that in this class, though. I have had a little bit of experience webscraping, but this was moreso just a small project I had done in my free time, and not a real introduction to harvesting data. Curating and taming data, though, that is my specialty. I simply learned how to do what I already knew how to do in python and java in R. Honestly, this is a bit weird, but it's my favorite part. Getting data into a nice form so that I can use it later is one of the most satisfying things in data science, in my mind. Regardless, I did learn little tips here and there, and I surely learned about how to use R packages to make my job easier. Additionally, I also learned regex, which I spent some time over the weekend learning, and now I can use it fairly effectively in other applications, which definitely comes in handy.

## Analysis

This is the section I thought was most closely tied to statistics, but given that quantitative text analysis is a type of data science, and that data science is closely tied to statistics, it only makes sense in hindsight. Regardless, I have had some experience with this section, only in inferential analysis, as I did AP stats and STA 112 here, most of which I forget, but I did not forget about the use of the hypothesis test, possibly because its logic is recycled in proofs by contradiction, which I learned in discrete math. Regardless, exploratory and predictive research was completely new to me. I learned everything about them in this class, I didn't even know exploratory research existed, and only knew vaguely about predictive research because of my surface-level knowledge of AI. I learned that exploratory research's goals are to generate insights into new ideas and possible correlations about the studied topic, to identify variables that could be at play, and to guide subsequent research. I had never realized that research branches off of itself like this, but again, in hindsight, it seems obvious. I also learned that predictive research is quite difficult, frankly. Building a model and iteratively improving it is time and labor intensive, especially if it turns out you have made a mistake and have to start all over again. Regardless, I like the idea of being able to plug in text into a model and it spitting out a prediction, and once complete, I surmise this research would be the most satisfying. 

## Communication

This is the section that I thought the least about before this semester. I figured that someone else would do it for me, a researcher, a scientist, someone qualified. I'm realizing now that it's my job, as the one conducting the research, to communicate to the world why it is valuable. This is not very difficult to me, as I feel that I am fairly good at presenting my ideas, most of the time, but the act of actually showing why my ideas matter is a bit uncomfortable to me. Before this semester, I was not comfortable talking about why my ideas have significance. It felt like a resume, or a job interview, where I have to sell myself, and prove why I should be hired above anyone else. Through presenting my prospectus and especially the impact it could have on people and the world at large, I have become more able, dare I say more confident, in my ideas, that they matter, and that they deserve to be listened to and taken seriously. I honestly can't be grateful enough for this. 

# Connect with my past

## Strategies

There are two main strategies I used that were beneficial to my learning. The first strategy that helped is, and this may seem odd, to "tough it out". If I'm stuck in some place and I just can't seem to figure some issue out, every second I spend trying to figure it out, is a second I spend learning about the tools I am using. This can be immensely valuable to my learning, especially because I expect to use R studio, R, git, github, or github pages again. I want to be keenly aware of what these tools are doing, and how I can make them work for me, not the other way around. On the other hand, though, if I am stuck in one place for an inordinate amount of time, a second, contrasting strategy is to be employed: be humble. If I'm stuck in a place where I am not getting what I need to get done, done, and I am not learning anything by continuing to struggle, it is okay to ask for help, as embarassing as that can be sometimes. Struggle on its own is only so valuable. The side effects of that struggle are why people consider it valuable. If you aren't getting those positive side effects: building character, learning, etc., then why struggle. This was the case with git integration with R studio, I realized there were not proper resources for me to use, so I asked you for help, and you gave it to me so I could continue. I still learnt about git and R studio, but I needed a bit of help, and I don't think there's anything wrong with that. 

## Resources

As far as the resources that were helpful in my learning, they differ depending on if we were directly coding or not. When we were coding, I was using whatever website I found on google for help with coding, as I knew what I wanted to do, and I knew how to do it in other programming languages, but I didn't know how to do it in R, especially tidyverse R. Another helpful tool was chatGPT. I definitely didn't use this a lot, but it was helpful occasionally. I would write the code in python or java, and ask chatGPT to translate it to R code, and I would include the packages I was using. This seemed like the most honest way to use this tool, and where I did use it, I noted it. When I wasn't coding, and even sometimes when I was, the most useful tool was by far the recipes. There was so much information in there, I would just search the section I needed, read a paragraph or two, sometimes copy some code, and I'd be off to the races. I can't understate how helpful these were. I do have to say, however, that reading these in their entirety was not a valuable use of my time, as I'd get only a surface level understanding of the process by the next day, as I'd forget most of the important details. The only way, in my mind, to make these details stick, is to actually use them and struggle with them for a time. 

## A difficult challenge

A challenging activity was the one of the final labs we actually coded for: Lab 05. I remember struggling for this for a couple of hours, primarily because it was difficult, yes, but also because I was unsure of what I was actually supposed to do. I wanted to jump right in and start coding, and that's exactly what I tried to do. After a while, though, I got stuck, and I wasn't sure what to do next. I slowed down, read the recipe, and got a better idea of what I was actually meant to do. I only wish I was a little bit more careful in my reading because although I finished the lab, I did too much "taming" the dataset, when I was supposed to just be acquiring the data. I also forgot to make a data origin file, which is regrettable. Regardless, though, slowing down and being a bit more humble definitely helped me though this challenge. 

# Looking ahead

I anticipate applying, in the future, much of my learning in this class, especially that of the tools we used, and the theoretical portion of the class. I will try to use git and github to manage my own projects, no matter how small, as I find myself often wanting to go back to a previous version, but having no backup, and being stuck. Sometimes, this can lead me to abandoning the project altogether, which happens more than I'd care to admit. Additionally, the ideals of reproducible research are very useful, and I'd like to create a private repo for myself that could help scaffold and organize projects I have in the future, instead of creating a new structure every time. This could allow me to be able to go back to projects I had worked on months ago and pick them back up much easier than before. Additionally, the effect of struggling with tools I haven't used before will transfer well to my own projects, and in fact, I have already noticed that I am much more willing to learn about a tool in order to use it, instead of just wanting to create a rudimentary version of the tool myself, just so I know how it works. I realize there is a place and time for that, but it isn't always the case that it will be the most effective use of my time. I also hope to use github pages in the future for a personal website, as I like the idea of it being infinitely customizable, or at least much more so than something like wordpress. Overall, there are many skills from this class, both hands-on and theoretical, that I can apply to my life right now.







